### ISSUE TITLE
Will not install

### ISSUE THREAD

**Issue by cybernexus** [sodexis/avatax_connector#2]
Does this module have a dependency that is not listed? 

The installation fails with the following error:

`Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 900, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 888, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 123, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 324, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 61, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/sale_avatax/__init__.py", line 4, in <module>
    import wizard
  File "/usr/lib/python2.7/dist-packages/openerp/addons/sale_avatax/wizard/__init__.py", line 3, in <module>
    import avalara_salestax_ping
  File "/usr/lib/python2.7/dist-packages/openerp/addons/sale_avatax/wizard/avalara_salestax_ping.py", line 4, in <module>
    from openerp.addons.avatax_connector.models.avalara_api import AvaTaxService
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 60, in load_module
    f, path, descr = imp.find_module(module_part, ad_paths)
ImportError: No module named avatax_connector`

It appears to be looking for avatax_connector, should this be included, is it a different package? I've been unable to find any reference to it.

**Comment by fhe-odoo** [comment]
Fixed in 04efa660a51fd89ee2e4472429cea28d947f04c1
